Repository wilhelmagren/finq, pull requests merged in 2023-10, with the labels that each got.

#27 feat(dataset): arg choosing OHLC data
  .gitignore
  finq/datasets/dataset.py
  tests/datasets/custom.py
Labels: enhancement

#30 fix(nasdaq): correct weekday diff logic in query params
  finq/datasets/dataset.py
  finq/datautil/nasdaq_requests.py
Labels: bug

#34 fix(tests): mock requests during unit testing
  finq/datasets/dataset.py
  tests/datasets/test_custom.py
  tests/datasets/test_omxs30.py
Labels: enhancement

#44 feat(log): add log ColoredFormatter, fix dataset issues
  finq/__init__.py
  finq/__version__.py
  finq/asset.py
  finq/datasets/dataset.py
  finq/datautil/nasdaq_requests.py
  finq/exceptions.py
  finq/log.py
  poetry.lock
  tests/datasets/mock_df.py
  tests/datasets/test_custom.py
  tests/datasets/test_ndx.py
  tests/datasets/test_omxs30.py
  tests/datasets/test_omxsbesgni.py
  tests/datasets/test_omxspi.py
Labels: bug, enhancement, python

#49 docs(finq): docstrings for Dataset, refactor, implement path utils
  finq/__init__.py
  finq/datasets/custom.py
  finq/datasets/dataset.py
  finq/datasets/ndx.py
  finq/datasets/omxs30.py
  finq/datasets/omxsbesgni.py
  finq/datasets/omxspi.py
  finq/datasets/snp500.py
  finq/datautil/__init__.py
  finq/datautil/nasdaq_utils.py
  finq/datautil/path_utils.py
  finq/exceptions.py
  pyproject.toml
  tests/datasets/test_custom.py
  tests/datasets/test_ndx.py
  tests/datasets/test_omxs30.py
  tests/datasets/test_omxsbesgni.py
  tests/datautil/test_nasdaq_utils.py
  tests/datautil/test_path_utils.py
Labels: bug, documentation, enhancement, python

#51 feat(dataset): enable passing proxy to yfinance Ticker on info fetch
  finq/datasets/dataset.py
  tests/datasets/test_custom.py
  tests/datasets/test_ndx.py
  tests/datasets/test_omxs30.py
  tests/datasets/test_omxsbesgni.py
  tests/datasets/test_omxspi.py
Labels: enhancement, python

#53 build(finq): prepare release v0.3.0
  README.md
  finq/__version__.py
  pyproject.toml
Labels: release
